# **PYTHON EDA**

#### **Import Libraries & Data**

In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('customer_shopping_behavior.csv')

#### **Data Exploration**

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [5]:
df.describe()  ## Only numerical columns described

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
df.describe(include='all')  ## All columns described

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

### **Check for missing values**

In [7]:
df.isna().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

### **Handling Missing Values**

In [8]:
df['Review Rating']= df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median))

In [9]:
df.isna().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

#### **Standardise Column Names**

In [10]:
df.columns= df.columns.str.lower()
df.columns= df.columns.str.replace(' ','_')
df= df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [11]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

### **Deriving Few Useful Columns**

In [12]:
# create a column age_group

labels= ['Young Adult','Adult','Middle-Aged','Senior']
df['age_group']= pd.qcut(df['age'], q=4, labels=labels)

In [13]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-Aged
1   19  Young Adult
2   50  Middle-Aged
3   21  Young Adult
4   45  Middle-Aged
5   46  Middle-Aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-Aged

In [14]:
# create column purchase_frequency_days

frequency_mapping={
    'Fortnightly':14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}
df['purchase_frequency_days']= df['frequency_of_purchases'].map(frequency_mapping)

In [15]:
df[['frequency_of_purchases','purchase_frequency_days']].head(10)

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

In [16]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [17]:
(df['discount_applied'] == df['promo_code_used']).all()
## both columns have similar data, so we can drop one column.

np.True_

In [18]:
 df = df.drop('promo_code_used', axis=1)

In [19]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   object
 3   item_purchased           3900 non-null   object
 4   category                 3900 non-null   object
 5   purchase_amount          3900 non-null   int64
 6   location                 3900 non-null   object
 7   size                     3900 non-null   object
 8   color                    3900 non-null   object
 9   season                   3900 non-null   object
 10  review_rating            3900 non-null   object
 11  subscription_status      3900 non-null   object
 12  shipping_type            3900 non-null   object
 13  discount_applied         3900 non-null   object
 14  previous_purchases       3900 non-null   int64
 15  payment_method           3900 non-null   object
 16  frequency_of_purchases   3900 non-null   object
 17  age_group                3900 non-null   category
 18  purchase_frequency_days  3900 non-null   int64
dtypes: category(1), int64(5), object(13)
memory usage: 552.6+ KB

# **CONNECTING WITH SQL DATABASE**

In [21]:
pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in c:\anaconda3\lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in c:\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

### Note: Use the code after this cell (toggled) for MSSQL, I had some issues with columns and other connectivity, so I had to clear those issues first.

In [ ]:
# #Use for normal MSSQL, if there is no error previously
# # Install required libraries

# from sqlalchemy import create_engine
# from urllib.parse import quote_plus

# # SQL Server connection
# username = "sa"
# password = "your_password"
# host = "localhost"
# port = "1433"
# database = "customer_behavior"

# # Note: requires Microsoft ODBC Driver installed separately on your machine
# driver = quote_plus("ODBC Driver 17 for SQL Server")
# engine = create_engine(f"mssql+pyodbc://{username}:{password}@{host},{port}/{database}?driver={driver}")

# # Write DataFrame to SQL Server
# df.to_sql("customer", engine, if_exists="replace", index=False)

# # Read back sample (SQL Server uses TOP instead of LIMIT)
# pd.read_sql("SELECT TOP 5 * FROM customer;", engine)

#### **I will first handle errors and then connect my table to sql database.**

In [42]:
import pyodbc
import pandas as pd
import numpy as np

# Step 1 — Clean dtypes
df_clean = df.copy()
df_clean["review_rating"] = pd.to_numeric(df_clean["review_rating"], errors="coerce").astype(float)

# Convert ALL non-numeric columns to str explicitly
for col in df_clean.columns:
    if df_clean[col].dtype.name == "category" or df_clean[col].dtype == "object":
        df_clean[col] = df_clean[col].astype(str)

print("Dtypes after fix:")
print(df_clean.dtypes)

# Step 2 — Build rows with EXPLICIT per-column casting (safest method)
def cast_value(val, dtype):
    if pd.isna(val) if not isinstance(val, str) else val in ("nan", "None", ""):
        return None
    if "int" in str(dtype):   return int(val)
    if "float" in str(dtype): return float(val)
    return str(val)

rows = []
for _, row in df_clean.iterrows():
    rows.append(tuple(
        cast_value(row[col], df_clean[col].dtype) for col in df_clean.columns
    ))

# Verify first row looks correct
print("\nFirst row sample:")
for col, val in zip(df_clean.columns, rows[0]):
    print(f"  {col}: {repr(val)} ({type(val).__name__})")

Dtypes after fix:
customer_id                  int64
age                          int64
gender                      object
item_purchased              object
category                    object
purchase_amount              int64
location                    object
size                        object
color                       object
season                      object
review_rating              float64
subscription_status         object
shipping_type               object
discount_applied            object
previous_purchases           int64
payment_method              object
frequency_of_purchases      object
age_group                   object
purchase_frequency_days      int64
dtype: object

First row sample:
  customer_id: 1 (int)
  age: 55 (int)
  gender: 'Male' (str)
  item_purchased: 'Blouse' (str)
  category: 'Clothing' (str)
  purchase_amount: 53 (int)
  location: 'Kentucky' (str)
  size: 'L' (str)
  color: 'Gray' (str)
  season: 'Winter' (str)
  review_rating: 3.1 (float)
  subscription_status: 'Yes' (str)
  shipping_type: 'Express' (str)
  discount_applied: 'Yes' (str)
  previous_purchases: 14 (int)
  payment_method: 'Venmo' (str)
  frequency_of_purchases: 'Fortnightly' (str)
  age_group: 'Middle-Aged' (str)
  purchase_frequency_days: 14 (int)

In [43]:
# Step 3 — Connect and insert
conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=127.0.0.1,1433;"
    "DATABASE=cust_behaviour;"
    "UID=ADNAN;"
    "PWD=Oracle@123;"
    "TrustServerCertificate=yes;"
)
cursor = conn.cursor()
table_name = "customer"

# Drop and recreate
cursor.execute(f"IF OBJECT_ID('{table_name}', 'U') IS NOT NULL DROP TABLE {table_name}")
conn.commit()

def pandas_type_to_sql(dtype):
    if "int"   in str(dtype): return "INT"
    if "float" in str(dtype): return "FLOAT"
    return "NVARCHAR(255)"

cols = ", ".join(f"[{col}] {pandas_type_to_sql(df_clean[col].dtype)}" for col in df_clean.columns)
cursor.execute(f"CREATE TABLE {table_name} ({cols})")
conn.commit()
print(f"\n✅ Table '{table_name}' created!")

# Insert
chunk_size = 500
placeholders = ", ".join(["?"] * len(df_clean.columns))
insert_sql = f"INSERT INTO {table_name} VALUES ({placeholders})"

for i in range(0, len(rows), chunk_size):
    chunk = rows[i:i+chunk_size]
    cursor.executemany(insert_sql, chunk)
    conn.commit()
    print(f"  ✅ Inserted rows {i+1}–{min(i+chunk_size, len(rows))}")

print(f"\n✅ All {len(df_clean)} rows loaded into '{table_name}' successfully!")
cursor.close()
conn.close()

✅ Table 'customer' created!
  ✅ Inserted rows 1–500
  ✅ Inserted rows 501–1000
  ✅ Inserted rows 1001–1500
  ✅ Inserted rows 1501–2000
  ✅ Inserted rows 2001–2500
  ✅ Inserted rows 2501–3000
  ✅ Inserted rows 3001–3500
  ✅ Inserted rows 3501–3900

✅ All 3900 rows loaded into 'customer' successfully!